name = "PauliOperators"
uuid = "be646426-f34c-4536-b1d4-a45a9633e6db"
authors = ["Nick Mayhall"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
